# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_auto_20170105_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='edit_date',
            field=models.DateField(null=True),
        ),
    ]
